const express = require('express');
const router = express.Router();
const productController = require('../controllers/productController');
router.post('/api/products', productController.addProduct);
router.get('/api/products', productController.allProduct);
router.get('/api/products/:id', productController.oneProduct);
router.get('/api/products/category/:category', productController.queryCategory);
router.get('/api/product', productController.searchProduct);
router.put('/api/products/:id', productController.editProduct);
router.delete('/api/products/:id', productController.deleteProduct);
module.exports = router;